- name: "Get distribution"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ host_os }}.yml"
  register: distribution_config

- name: "Run tasks for {{ host_os }}"
  ansible.builtin.include_tasks: "{{ host_os }}.yml"
  when: distribution_config.stat.exists

- name: Create firefox 'Personal' profile
  ansible.builtin.command:
    cmd: firefox -CreateProfile Personal
  register: personal
  changed_when: personal.rc != 0

- name: Create firefox 'Work' profile
  ansible.builtin.command:
    cmd: firefox -CreateProfile Work
  register: work
  changed_when: work.rc != 0
