services:
  ansible-arch:
    build:
      context: .
      dockerfile: Dockerfile.archlinux
    container_name: ansible-arch-dev
    # environment:
    tty: true

  ansible-ubuntu:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    container_name: ansible-ubuntu-dev
    # environment:
    tty: true
