---
- name: Dotfiles config
  hosts: localhost
  connection: local

  vars:
    dotfiles_dir: "{{ github_dir }}/dotfiles"
    downloads: "{{ ansible_env.HOME }}/Downloads"
    github_dir: "{{ ansible_env.HOME }}/Documents/github"

  pre_tasks:
    - name: Detect host system
      ansible.builtin.import_tasks: pre_tasks/whoami.yml
      tags:
        - always

  tasks:
    - name: Set roles
      ansible.builtin.set_fact:
        run_roles: >-
          {{ (ansible_run_tags if ansible_run_tags != ['all'] else default_roles)
             | difference(exclude_roles | default([]))
             | sort }}
      tags:
        - always

    - name: Run roles
      ansible.builtin.include_role:
        name: "{{ roles_item }}"
        apply:
          tags: "{{ roles_item }}"
      loop: "{{ run_roles }}"
      loop_control:
        loop_var: roles_item
      tags:
        - always
