- name: Install drivers
  ansible.builtin.import_tasks: install_dirvers.yml
  tags:
    - archlinux

- name: Install default system packages
  ansible.builtin.import_tasks: install_default_packages.yml
  tags:
    - archlinux
    - arch-system-packages

- name: Install cli packages
  ansible.builtin.import_tasks: install_cli_packages.yml
  tags:
    - archlinux
    - arch-cli-packages
