---
- name: Clone dotfiles repository
  ansible.builtin.git:
    repo: "https://github.com/yourusername/dotfiles.git"
    dest: "{{ ansible_env.HOME }}/dotfiles"
    update: yes

- name: Clone another important repository
  ansible.builtin.git:
    repo: "https://github.com/yourusername/another-repo.git"
    dest: "{{ ansible_env.HOME }}/another-repo"
    update: yes
