- name: Ensure install xorg packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  loop:
    - xdotool
    - xorg-xev
    - xorg-xinit
    - xorg-xrandr
    - xorg-server
    - xorg-xsetroot

- name: Ensure remove wayland
  become: true
  community.general.pacman:
    name:
      - waybar
    state: absent
