- name: Ensure install xorg packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  loop:
    - feh
    - sxhkd
    - picom
    - bspwm
    - xdotool
    - polybar
    - pcmanfm
    - xorg-xev
    - breeze-gtk
    - ueberzugpp
    - xorg-xinit
    - xorg-xrandr
    - xorg-server
    - breeze-icons
    - lxappearance
    - xorg-xsetroot
    - capitaine-cursors

- name: Ensure remove wayland
  become: true
  community.general.pacman:
    name:
      - waybar
    state: absent
