---
- name: Ensure install xorg packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  loop:
    - xorg-server
    - xorg-xev
    - xorg-xinit
    - xorg-xrandr
    - xorg-xsetroot
    - bspwm
    - sxhkd
    - breeze-gtk
    - breeze-icons
    - capitaine-cursors
    - picom
    - lxappearance
    - feh
    - ueberzugpp

- name: Ensure intall aur packages
  community.general.pacman:
    name: "{{ item }}"
    state: present
    executable: paru
  loop:
    - bun-bin
    - vesktop-bin

- name: Ensure remove wayland
  become: true
  community.general.pacman:
    name:
      - waybar
    state: absent
