---
- name: Ensure clone github repositories
  ansible.builtin.git:
    update: false
    recursive: true
    dest: "{{ github_dir }}/{{ item.repo }}"
    version: "{{ item.branch | default('main') }}"
    repo: "git@personal.github:pazbryant/{{ item.repo }}.git"
  loop:
    - { repo: "dwm", branch: "main" }
    - { repo: "pass", branch: "main" }
    - { repo: "notes", branch: "main" }
    - { repo: "media", branch: "main" }
    - { repo: "youtube", branch: "main" }
    - { repo: "leetcode", branch: "main" }
    - { repo: "portfolio", branch: "main" }
    - { repo: "boilerplate", branch: "main" }
    - { repo: "ansible-dots", branch: "main" }

- name: Ensule neovim symlink is created in github folder
  ansible.builtin.file:
    src: "{{ github_dir }}/dotfiles/.config/nvim"
    dest: "{{ github_dir }}/nvim"
    state: link
