---
- name: Ensure clone github repositories
  ansible.builtin.git:
    update: false
    recursive: true
    dest: "{{ github_dir }}/{{ item.repo }}"
    version: "{{ item.branch | default('main') }}"
    repo: "git@personal.github:pazbryant7/{{ item.repo }}.git"
  loop:
    - { repo: "pass", branch: "main" }
    - { repo: "notes", branch: "main" }
    - { repo: "media", branch: "main" }
    - { repo: "youtube", branch: "main" }
    - { repo: "pass-dev", branch: "main" }
    - { repo: "portfolio", branch: "main" }
    - { repo: "boilerplate", branch: "main" }
    - { repo: "ansible-dots", branch: "main" }

- name: Ensure clone neovim configurations
  ansible.builtin.git:
    update: false
    recursive: true
    dest: "{{ xdg_config_dir }}/{{ item.repo }}"
    version: "{{ item.branch | default('main') }}"
    repo: "git@personal.github:pazbryant7/{{ item.repo }}.git"
  loop:
    - { repo: "vim", branch: "main" }
    - { repo: "nvim", branch: "main" }
