---
- name: Ensure clone and setup dotfiles
  ansible.builtin.git:
    update: false
    version: main
    recursive: true
    accept_newhostkey: true
    dest: "{{ dotfiles_dir }}"
    repo: "git@personal.github:pazbryant/dotfiles.git"
  notify:
    - Setup dotfiles with stow
  tags: dotfiles
