---
- name: Ensure install wayland packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  loop:
    - wayland
    - sway
    - swaybg

- name: Ensure intall aur packages
  community.general.pacman:
    name: "{{ item }}"
    state: present
    executable: paru
  loop:
    - bun-bin
    - vesktop-bin
  tags: wayland

- name: Ensure remove xorg packages
  community.general.pacman:
    name:
      - xorg-server
      - xorg-xev
      - xorg-xinit
      - xorg-xrandr
      - xorg-xsetroot
      - bspwm
      - sxhkd
      - breeze-gtk
      - breeze-icons
      - capitaine-cursors
      - picom
      - lxappearance
      - feh
      - ueberzugpp
    state: absent
  tags: wayland
