- name: Import ssh configuration file
  ansible.builtin.import_tasks: configuration.yml
  tags:
    - ssh

- name: Import private keys to host
  ansible.builtin.import_tasks: send_to_host.yml
  tags:
    - ssh
