- name: Ensure required directories exist
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - /etc/pacman.d/hooks/

- name: Import pacman hook
  become: true
  ansible.builtin.copy:
    src: files/archlinux/update-software.hook
    dest: "/etc/pacman.d/hooks/update-software.hook"
    owner: root
    group: root
    mode: "0644"
    force: false

- name: Ensure pacman ParallelDownloads is set to '5'
  become: true
  ansible.builtin.lineinfile:
    dest: /etc/pacman.conf
    regexp: "^#ParallelDownloads = 5"
    line: "ParallelDownloads = 5"
    create: true
    backup: true
    owner: root
    group: root
    mode: "0644"
