- name: Import pacman hooks
  become: true
  ansible.builtin.copy:
    src: files/archlinux/update-software.hook
    dest: "/etc/pacman.d/hooks/update-software.hook"
    owner: root
    group: root
    mode: "0644"

- name: Fix obinslab app image
  become: true
  ansible.builtin.copy:
    src: files/archlinux/obinslab.starter.rules
    dest: "/etc/udev/rules.d/obinskit-kdb.rules"
    owner: root
    group: root
    mode: "0644"

- name: Import vconsole custom keyboard (engish)
  become: true
  ansible.builtin.copy:
    src: files/archlinux/xkb/bryant-dvorak.map
    dest: "/usr/share/kbd/keymaps/i386/dvorak/bryant-dvorak.map"
    owner: root
    group: root
    mode: "0644"

- name: Import system custom keyboard (english)
  become: true
  ansible.builtin.copy:
    src: files/archlinux/xkb/bryant-dvorak
    dest: "/usr/share/X11/xkb/symbols/bryant-dvorak"
    owner: root
    group: root
    mode: "0644"

- name: Import system custom keyboard (spanish)
  become: true
  ansible.builtin.copy:
    src: files/archlinux/xkb/bryant-dvorak-itl
    dest: "/usr/share/X11/xkb/symbols/bryant-dvorak-itl"
    owner: root
    group: root
    mode: "0644"

# NOTE: when no mode is set it will use the mode of the already existing files

- name: Import system custom configuration (spanish)
  become: true
  ansible.builtin.copy:
    src: files/archlinux/etc/00-keyboard.conf
    dest: "/etc/X11/xorg.conf.d/00-keyboard.conf"

- name: Import vconsole custom keyboard configuration (spanish)
  become: true
  ansible.builtin.copy:
    src: files/archlinux/etc/vconsole.conf
    dest: "/etc/vconsole.conf"
