---
- name: "Checking for Distribution Config: {{ ansible_distribution | lower }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution | lower }}.yml"
  register: distribution_config

- name: "Run Tasks: {{ ansible_distribution | lower }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}.yml"
  when: distribution_config.stat.exists
