---
- name: Ensure zsh is installed
  become: true
  community.general.pacman:
    name: "zsh"
    state: present

- name: Handle shell output with return code
  become: true
  ansible.builtin.shell: chsh -s $(which zsh)
  register: zsh
  changed_when: zsh.rc != 0
