---
- name: Installing stow
  become: true
  community.general.pacman:
    name:
      - stow
    state: present

- name: Clone dotfiles
  ansible.builtin.git:
    update: no
    version: main
    recursive: true
    accept_newhostkey: true
    dest: "{{ dotfiles_dir }}"
    repo: "git@personal.github:pazbryant/dotfiles.git"

- name: Stow dotfiles
  shell: cd {{ dotfiles_dir }} && stow .
