- name: Clone GitHub repositories
  ansible.builtin.git:
    update: no
    dest: "{{ github_dir }}/{{ item.repo }}"
    version: "{{ item.branch | default('main') }}"
    repo: "git@personal.github:pazbryant/{{ item.repo }}.git"
  loop:
    - { repo: "pass", branch: "main" }
    - { repo: "nvim", branch: "main" }
    - { repo: "notes", branch: "main" }
    - { repo: "portfolio", branch: "main" }
    - { repo: "boilerplate", branch: "main" }
