---
- name: "Get distribution"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ host_os }}.yml"
  register: distribution_config

- name: "Run tasks for {{ host_os }}"
  ansible.builtin.include_tasks: "{{ host_os }}.yml"
  when: distribution_config.stat.exists

- name: Enable ufw
  become: true
  community.general.ufw:
    state: enabled

- name: Set default incoming policy to deny
  become: true
  community.general.ufw:
    direction: incoming
    default: deny

- name: Set default outgoing policy to allow
  become: true
  community.general.ufw:
    direction: outgoing
    default: allow

- name: Allow all traffic from 192.168.0.0/24
  become: true
  community.general.ufw:
    rule: allow
    from_ip: 192.168.0.0/24

- name: Allow Deluge from anywhere
  become: true
  community.general.ufw:
    rule: allow
    app: Deluge

- name: Limit SSH from anywhere
  become: true
  community.general.ufw:
    rule: limit
    app: SSH
