- name: Ensure Backup-notes cron job exists
  ansible.builtin.cron:
    name: "Backup notes"
    minute: "0"
    hour: "*"
    job: "{{ ansible_env.HOME }}/bin/crontab/backup-notes > /tmp/cron-backup-notes 2>&1" # Added the redirection
    state: present
    user: "{{ ansible_user_id }}"
