- name: Ensure Backup-notes cron job exists
  ansible.builtin.cron:
    name: "Backup notes"
    minute: "0"
    hour: "*/2"
    job: "{{ ansible_env.HOME }}/bin/crontab/backup-notes"
    state: present

- name: Ensure Backup media cron job exists
  ansible.builtin.cron:
    name: "Backup media"
    minute: "0"
    hour: "*/5"
    job: "{{ ansible_env.HOME }}/bin/crontab/backup-media"
    state: present
