- name: Setup dotfiles with stow
  ansible.builtin.command:
    cmd: >
      stow --dir="{{ dotfiles_dir }}"
      --target="{{ ansible_user_dir }}"
      --adopt --restow .
  args:
    chdir: "{{ dotfiles_dir }}"
  register: stowstdr
  changed_when: stowstdr.rc != 0
