---
- name: Ensure base development packages are installed
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  loop:
    - ufw
    - grub
    - base
    - tmux
    - pass
    - stow
    - linux
    - xclip
    - man-db
    - cronie
    - neovim
    - pipewire
    - linux-lts
    - base-devel
    - openresolv
    - wireplumber
    - otf-overpass
    - terminus-font
    - xdg-user-dirs
    - pipewire-alsa
    - linux-headers
    - pipewire-jack
    - zram-generator
    - linux-firmware
    - noto-fonts-emoji
    - linux-lts-headers
    - gst-plugin-pipewire

- name: Ensure install xorg packages
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  loop:
    - feh
    - sxhkd
    - picom
    - bspwm
    - xdotool
    - xorg-xev
    - breeze-gtk
    - ueberzugpp
    - xorg-xinit
    - xorg-xrandr
    - xorg-server
    - breeze-icons
    - lxappearance
    - xorg-xsetroot
    - capitaine-cursors
  when: host_wm == "bspwm"

- name: Ensure remove wayland
  become: true
  community.general.pacman:
    name:
      - waybar
    state: absent
  when: host_wm == "bspwm"
