---
- name: Ensure base development packages are installed
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  loop:
    - ufw
    - base
    - tmux
    - grub
    - xclip
    - linux
    - rtkit
    - dunst
    - cronie
    - neovim
    - man-db
    - pipewire
    - linux-lts
    - openresolv
    - base-devel
    - wireplumber
    - otf-overpass
    - pipewire-jack
    - linux-headers
    - pipewire-alsa
    - terminus-font
    - xdg-user-dirs
    - linux-firmware
    - zram-generator
    - pipewire-pulse
    - noto-fonts-emoji
    - linux-lts-headers
    - gst-plugin-pipewire

- name: Create the `aur_builder` user
  become: true
  ansible.builtin.user:
    name: aur_builder
    create_home: true
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    create: true
    mode: "0644"
    validate: "visudo -cf %s"

- name: Install paru using makepkg if it isn't installed already
  become: true
  kewlfft.aur.aur:
    name: paru
    use: makepkg
    state: present
  become_user: aur_builder
