---
- name: Installing stow
  become: true
  community.general.pacman:
    name:
      - stow
    state: present

- name: Clone dotfiles
  ansible.builtin.git:
    repo: "git@personal.github:pazbryant/dotfiles.git"
    dest: "{{ github_dir }}/dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
# - name: Stow dotfiles
#   shell: cd {{ github_dir }}/dotfiles && ./ubuntu
