- name: Ensure GPG directory exists
  file:
    path: "{{ ansible_env.HOME }}/.gnupg"
    state: directory
    mode: "0700"

- name: Deploy GPG private_key key
  copy:
    dest: "{{ ansible_env.HOME }}/.gnupg/private_key.asc"
    mode: "0600"
    content: "{{ lookup('file', '.secrets/gpg/private-key.asc') }}"
