- name: Setup ssh
  include_tasks: private/deploy_ssh_private_keys.yml
  tags:
    - private

- name: Setup gpg
  include_tasks: private/deploy_gpg_private_keys.yml
  tags:
    - private

- name: Setup dotfiles
  include_tasks: github/clone_dotfiles.yml
  tags:
    - dotfiles

- name: Setup github personal
  include_tasks: github/clone_personal.yml
  tags:
    - dotfiles

- name: Setup github work
  include_tasks: github/clone_work.yml
  tags:
    - dotfiles
