- name: Deploy ssh private key
  ansible.builtin.import_tasks: deploy_ssh_private_keys.yml
  tags:
    - always

- name: Deploy gpg private key
  ansible.builtin.import_tasks: deploy_gpg_private_keys.yml
  tags:
    - always

- name: Clone default github dotfiles
  ansible.builtin.import_tasks: clone_github_dotfiles.yml
  tags:
    - always
  register: clone_result
  failed_when: >
    clone_result is failed and
    "'Repository already exists'" not in (clone_result.stderr | default(''))

- name: Clone github personal repositories
  ansible.builtin.import_tasks: clone_github_personal_repositories.yml
  tags:
    - always
  register: clone_result
  failed_when: >
    clone_result is failed and
    "'Repository already exists'" not in (clone_result.stderr | default(''))
