---
- name: "Get distribution"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ host_os }}.yml"
  register: distribution_config

- name: "Run tasks for {{ host_os }}"
  ansible.builtin.include_tasks: "{{ host_os }}.yml"
  when: distribution_config.stat.exists

- name: Ensure the docker group exists
  become: true
  ansible.builtin.group:
    name: docker
    state: present

- name: Ensure the user is in the docker group
  become: true
  ansible.builtin.user:
    name: "{{ host_user }}"
    groups: docker
    append: true

- name: Enable and start docker service
  ansible.builtin.systemd:
    name: docker.service
    enabled: true
    state: started
