---
- name: Register current user
  ansible.builtin.set_fact:
    host_user: "{{ ansible_user_id }}"
  when: host_user is not defined

- name: Register current OS
  ansible.builtin.set_fact:
    host_os: "{{ ansible_distribution | lower }}"
  when: host_os is not defined
