- name: Ensure gpg directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.gnupg"
    state: directory
    mode: "0700"

- name: Ensure gpg key is imported
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.gnupg/private_key.asc"
    mode: "0600"
    content: "{{ lookup('file', '.secrets/gpg/private-key.asc') }}"
  tags: gpg
