- name: "Get distribution"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ host_os }}.yml"
  register: distribution_config

- name: "Run tasks for {{ host_os }}"
  ansible.builtin.include_tasks: "{{ host_os }}.yml"
  when: distribution_config.stat.exists

- name: Ensure xdg_config directory exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    mode: "0700"

- name: Import rclone config file
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.config/rclone/rclone.conf"
    mode: "0700"
    content: "{{ lookup('file', '.secrets/xdg_config/rclone/rclone.conf') }}"
    force: false
