- name: Ensure common cli tools are installed
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  loop:
    - jq
    - fd
    - go
    - uv
    - lua
    - mpd
    - eza
    - xsv
    - mpv
    - fzf
    - mpc
    - git
    - feh
    - yazi
    - rofi
    - lsof
    - code
    - 7zip
    - maim
    - tree
    - less
    - fish
    - tmux
    - stow
    - glow
    - sqlc
    - rust
    - dust
    - picom
    - rsync
    - pgcli
    - atuin
    - aria2
    - nsxiv
    - bottom
    - zoxide
    - xcolor
    - ffmpeg
    - yt-dlp
    - gopass
    - poppler
    - calibre
    - zathura
    - firefox
    - ncmpcpp
    - poppler
    - lazygit
    - pcmanfm
    - ripgrep
    - luarocks
    - nwg-look
    - libpulse
    - starship
    - screenkey
    - syncthing
    - bandwhich
    - alacritty
    - fastfetch
    - streamlink
    - python-pip
    - breeze-gtk
    - ueberzugpp
    - imagemagick
    - qbittorrent
    - qutebrowser
    - pavucontrol
    - breeze-icons
    - android-tools
    - pacman-contrib
    - translate-shell
    - capitaine-cursors
    - zathura-pdf-mupdf
    - ffmpegthumbnailer
    - ttf-cascadia-code-nerd

- name: Install aur packages using paru
  kewlfft.aur.aur:
    use: paru
    name: "{{ item }}"
    state: present
  loop:
    - wego
    - bun-bin
    - litecli
    - ani-cli
    - datagrip
    - brave-bin
    - bruno-bin
    - lazydocker
    - dragon-drop
    - postman-bin
    - vesktop-bin
    - datagrip-jre
    - rofi-greenclip

- name: Setup bandwhich to run without sudo
  become: true
  ansible.builtin.command:
    cmd:
      setcap cap_sys_ptrace,cap_dac_read_search,cap_net_raw,cap_net_admin+ep
      $(command -v bandwhich)
  register: bandwhich_stdout
  changed_when: bandwhich_stdout.rc != 0
