- name: Ensure common cli tools are installed
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  loop:
    - jq
    - fd
    - go
    - eza
    - bob
    - bat
    - imv
    - mpv
    - fzf
    - mpc
    - git
    - less
    - tree
    - 7zip
    - maim
    - dust
    - rofi
    - zbar
    - tmux
    - stow
    - pass
    - yazi
    - yarn
    - atuin
    - rsync
    - zoxide
    - rclone
    - xcolor
    - ncmpcpp
    - firefox
    - pcmanfm
    - zathura
    - lazygit
    - calibre
    - udiskie
    - polybar
    - poppler
    - ripgrep
    - libpulse
    - pass-otp
    - chromium
    - obsidian
    - starship
    - fastfetch
    - screenkey
    - hyperfine
    - bandwhich
    - unclutter
    - alacritty
    - syncthing
    - python-pip
    - qbittorrent
    - imagemagick
    - python-pipx
    - pavucontrol
    - speedtest-cli
    - translate-shell
    - telegram-desktop
    - zathura-pdf-mupdf
    - ffmpegthumbnailer

- name: Install cargo packages
  become: true
  community.general.cargo:
    name: "{{ item }}"
    state: present
  loop:
    - fnm

- name: Install pipx packages
  become: true
  community.general.cargo:
    name: "{{ item }}"
    state: present
  loop:
    - pgcli
    - litecli

- name: Install aur packages with paru
  community.general.pacman:
    name: "{{ item }}"
    executable: paru
  loop:
    - bun-bin
    - vesktop-bin
    - ani-cli
    - bun-bin
    - lazydocker
    - obinskit
    - paru
    - paru-debug
    - ttf-maple
    - vesktop-bin
