- name: Ensure common cli tools are installed
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  loop:
    - jq
    - fd
    - go
    - mpc
    - fzf
    - git
    - imv
    - mpv
    - bat
    - bob
    - yarn
    - yazi
    - zbar
    - rofi
    - rust
    - tree
    - less
    - maim
    - 7zip
    - dust
    - atuin
    - rsync
    - xcolor
    - rclone
    - zoxide
    - polybar
    - poppler
    - dbeaver
    - udiskie
    - ripgrep
    - calibre
    - pcmanfm
    - firefox
    - zathura
    - lazygit
    - ncmpcpp
    - libpulse
    - luarocks
    - chromium
    - obsidian
    - pass-otp
    - syncthing
    - unclutter
    - alacritty
    - bandwhich
    - hyperfine
    - screenkey
    - fastfetch
    - python-pip
    - pavucontrol
    - imagemagick
    - python-pipx
    - qbittorrent
    - speedtest-cli
    - translate-shell
    - telegram-desktop
    - zathura-pdf-mupdf
    - ffmpegthumbnailer

- name: Install aur packages with paru
  community.general.pacman:
    name: "{{ item }}"
    executable: paru
  loop:
    - bun-bin
    - vesktop-bin
