- name: Ensure common cli tools are installed
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  loop:
    - jq
    - uv
    - xh
    - fd
    - go
    - mpc
    - git
    - feh
    - mpv
    - bat
    - fzf
    - mpd
    - eza
    - sqlc
    - wget
    - rust
    - tmux
    - stow
    - yazi
    - code
    - rofi
    - 7zip
    - maim
    - less
    - tree
    - nsxiv
    - atuin
    - rsync
    - lua51
    - pgcli
    - ffmpeg
    - gopass
    - xcolor
    - zoxide
    - bottom
    - poppler
    - ripgrep
    - lazygit
    - ncmpcpp
    - poppler
    - calibre
    - zathura
    - starship
    - luarocks
    - libpulse
    - alacritty
    - syncthing
    - fastfetch
    - screenkey
    - streamlink
    - python-pip
    - pavucontrol
    - qbittorrent
    - imagemagick
    - android-tools
    - networkmanager
    - translate-shell
    - zathura-pdf-mupdf
    - ffmpegthumbnailer
    - ttf-cascadia-code-nerd

- name: Install aur packages using paru
  kewlfft.aur.aur:
    use: paru
    name: "{{ item }}"
    state: present
  loop:
    - wego
    - ani-cli
    - bun-bin
    - litecli
    - ttf-maple
    - brave-bin
    - lazydocker
    - vesktop-bin
    - postman-bin
    - dragon-drop
    - thorium-browser-bin
