- name: Ensure common cli tools are installed
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  loop:
    - go
    - xh
    - fd
    - fzf
    - eza
    - bob
    - mpd
    - bat
    - imv
    - mpc
    - git
    - mpv
    - less
    - tree
    - 7zip
    - maim
    - dust
    - rofi
    - tmux
    - hurl
    - stow
    - yarn
    - yazi
    - pass
    - code
    - pgcli
    - lua51
    - rsync
    - atuin
    - rclone
    - bottom
    - xcolor
    - zoxide
    - gopass
    - ffmpeg
    - calibre
    - zathura
    - ncmpcpp
    - lazygit
    - pcmanfm
    - udiskie
    - poppler
    - polybar
    - ripgrep
    - libpulse
    - chromium
    - luarocks
    - starship
    - obsidian
    - fastfetch
    - bandwhich
    - screenkey
    - hyperfine
    - syncthing
    - unclutter
    - alacritty
    - python-pip
    - imagemagick
    - python-pipx
    - imagemagick
    - qbittorrent
    - pavucontrol
    - speedtest-cli
    - networkmanager
    - translate-shell
    - telegram-desktop
    - zathura-pdf-mupdf
    - ffmpegthumbnailer

- name: Install aur packages using paru
  kewlfft.aur.aur:
    use: paru
    name: "{{ item }}"
    state: present
  loop:
    - bun-bin
    - ani-cli
    - obinskit
    - ttf-maple
    - lazydocker
    - vesktop-bin
  ignore_errors: true

- name: Install packages with pipx
  community.general.pipx:
    name: "{{ item }}"
    state: present
  loop:
    - poetry
  ignore_errors: true
