- name: Ensure common cli tools are installed
  become: true
  community.general.pacman:
    name: "{{ item }}"
    state: present
  loop:
    - uv
    - xh
    - fd
    - go
    - mpc
    - git
    - mpv
    - bat
    - imv
    - fzf
    - mpd
    - eza
    - bob
    - hurl
    - tmux
    - stow
    - glow
    - yazi
    - code
    - yarn
    - rofi
    - 7zip
    - maim
    - less
    - dust
    - tree
    - atuin
    - rsync
    - lua51
    - piper
    - pgcli
    - ffmpeg
    - gopass
    - xcolor
    - zoxide
    - rclone
    - bottom
    - poppler
    - udiskie
    - polybar
    - ripgrep
    - pcmanfm
    - lazygit
    - ncmpcpp
    - firefox
    - poppler
    - calibre
    - zathura
    - starship
    - luarocks
    - obsidian
    - libpulse
    - alacritty
    - unclutter
    - syncthing
    - hyperfine
    - fastfetch
    - bandwhich
    - screenkey
    - python-pip
    - pavucontrol
    - qbittorrent
    - imagemagick
    - imagemagick
    - python-pipx
    - speedtest-cli
    - networkmanager
    - translate-shell
    - zathura-pdf-mupdf
    - ffmpegthumbnailer
    - ttf-cascadia-code-nerd

- name: Install aur packages using paru
  kewlfft.aur.aur:
    use: paru
    name: "{{ item }}"
    state: present
  loop:
    - wego
    - bun-bin
    - ani-cli
    - ttf-maple
    - lazydocker
    - dragon-drop
    - postman-bin
    - vesktop-bin
    - thorium-browser-bin
    - ungoogled-chromium-bin
