- name: "Get distribution"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ host_os }}.yml"
  register: distribution_config

- name: "Run tasks for {{ host_os }}"
  ansible.builtin.include_tasks: "{{ host_os }}.yml"
  when: distribution_config.stat.exists

- name: Install packages using cargo
  community.general.cargo:
    name: "{{ item }}"
    state: present
  loop:
    - fnm
    - petname

- name: Install packages using uv
  moreati.uv.pip:
    name: "{{ item }}"
    virtualenv: ~/venv
  loop:
    - spotdl
    - names-generator
