- name: Ensure common cli tools are installed
  become: true
  community.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - jq
    - fd
    - go
    - eza
    - bob
    - bat
    - imv
    - mpv
    - fzf
    - mpc
    - git
    - less
    - tree
    - 7zip
    - maim
    - dust
    - rust
    - rofi
    - zbar
    - tmux
    - stow
    - pass
    - yazi
    - yarn
    - atuin
    - rsync
    - zoxide
    - rclone
    - xcolor
    - ncmpcpp
    - firefox
    - pcmanfm
    - zathura
    - lazygit
    - calibre
    - dbeaver
    - udiskie
    - polybar
    - poppler
    - ripgrep
    - libpulse
    - pass-otp
    - starship
    - chromium
    - obsidian
    - luarocks
    - fastfetch
    - screenkey
    - hyperfine
    - bandwhich
    - unclutter
    - alacritty
    - syncthing
    - python-pip
    - qbittorrent
    - imagemagick
    - python-pipx
    - pavucontrol
    - speedtest-cli
    - translate-shell
    - telegram-desktop
    - zathura-pdf-mupdf
    - ffmpegthumbnailer